name = "lesson_2_schema_validation"
description = "Lesson 2: Schema Validation - Validate documents with schemas"
version = "0.1.0"

authors = ["Rebecca Wise"]
maintainers = ["Rebecca Wise <rebecca@berkeleynerd.com>"]
maintainers-logins = ["berkeleynerd"]
licenses = "MIT OR Apache-2.0 WITH LLVM-exception"

executables = ["lesson_1_basic_parsing", "lesson_2_schema_validation"]

[build-switches]
"*".ada_version = "Ada2022"

[[depends-on]]
sml = "=0.1.0"

[[depends-on]]
sml_io = "=0.1.0"
